// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace MoM.Migrations
{
    [DbContext(typeof(MoMContext))]
    [Migration("20220119030727_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Odsek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Br_radnika")
                        .HasColumnType("int")
                        .HasColumnName("Br. radnika");

                    b.Property<int>("Br_slucajeva")
                        .HasColumnType("int")
                        .HasColumnName("Br. slučajeva");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime");

                    b.Property<int>("Sprat")
                        .HasColumnType("int")
                        .HasColumnName("Br. sprata");

                    b.HasKey("ID");

                    b.ToTable("Odsek");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Ime");

                    b.Property<int?>("OdsekID")
                        .HasColumnType("int");

                    b.Property<string>("Pol")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Pol");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Prezime");

                    b.Property<string>("brLegitimacije")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("Br. legitimacije");

                    b.Property<int>("godRodj")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Godina rođenja");

                    b.HasKey("ID");

                    b.HasIndex("OdsekID");

                    b.ToTable("Radnik");
                });

            modelBuilder.Entity("Models.Slucaj", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OdsekID")
                        .HasColumnType("int");

                    b.Property<int?>("RadnikID")
                        .HasColumnType("int");

                    b.Property<string>("kodnoIme")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kodno ime");

                    b.Property<string>("nivoPov")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nivo poverljivosti");

                    b.Property<string>("opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Kratak opis");

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("id");

                    b.HasIndex("OdsekID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Slučaj");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.HasOne("Models.Odsek", "Odsek")
                        .WithMany("Radnici")
                        .HasForeignKey("OdsekID");

                    b.Navigation("Odsek");
                });

            modelBuilder.Entity("Models.Slucaj", b =>
                {
                    b.HasOne("Models.Odsek", "Odsek")
                        .WithMany("Slucajevi")
                        .HasForeignKey("OdsekID");

                    b.HasOne("Models.Radnik", "Radnik")
                        .WithMany("Slucajevi")
                        .HasForeignKey("RadnikID");

                    b.Navigation("Odsek");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("Models.Odsek", b =>
                {
                    b.Navigation("Radnici");

                    b.Navigation("Slucajevi");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Navigation("Slucajevi");
                });
#pragma warning restore 612, 618
        }
    }
}
